.TH ALTER 1 2023-10-04 1.0.0 "Utilidades de paginador del manual"
.SH NOMBRE
alter \- Envía una petición a un socket e imprime la respuesta por salida estándar.

.SH SINOPSIS
.B alter
[\fIOpción\fR]...

.SH DESCRIPCIÓN
Esta sección describe en detalle lo que hace el comando.

.SH OPCIONES
Aquí se enumeran y describen las opciones del comando.

.SH EJEMPLOS
Se muestran ejemplos de uso del comando.

.SH AUTOR
Tu nombre o información de contacto.

.SH HISTORIA
Información sobre la historia o versiones del comando.

.SH LICENCIA
GPLv3
